version: "2.4"

services:
  mariadb :
    image: 'mariadb:10.6.4'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: pwd

      MYSQL_DATABASE: ldap_slack_sync
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "0.0.0.0:3306:3306"
